CREATE TABLE `alertas` (
	`id` int AUTO_INCREMENT NOT NULL,
	`tipo_alerta` enum('sobrepreco','vinculo_familiar','concentracao_fornecedor','desvio_geografico','funcionario_fantasma','inconsistencia_patrimonial','padrão_suspeito','outro') NOT NULL,
	`parlamentarId` int,
	`contratoId` int,
	`emendaId` int,
	`titulo` varchar(255) NOT NULL,
	`descricao` text,
	`valorEnvolvido` varchar(30) DEFAULT '0',
	`scoreRisco` varchar(10) NOT NULL,
	`nivelRisco_alerta` enum('baixo','medio','alto','critico') NOT NULL,
	`status_alerta` enum('novo','analisando','confirmado','descartado','investigando') DEFAULT 'novo',
	`fonteOrigem` varchar(100),
	`dataDeteccao` timestamp DEFAULT (now()),
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `alertas_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `contratos` (
	`id` int AUTO_INCREMENT NOT NULL,
	`numeroContrato` varchar(50) NOT NULL,
	`orgaoContratante` varchar(255) NOT NULL,
	`empresaContratada` varchar(255) NOT NULL,
	`valorContrato` varchar(30) NOT NULL,
	`valorPago` varchar(30) DEFAULT '0',
	`dataAssinatura` timestamp NOT NULL,
	`dataVencimento` timestamp,
	`descricao` text,
	`objeto` varchar(500),
	`scoreRisco` varchar(10) DEFAULT '0',
	`nivelRisco_contrato` enum('baixo','medio','alto','critico') DEFAULT 'baixo',
	`temSobrepreco` int DEFAULT 0,
	`percentualSobrepreco` varchar(10) DEFAULT '0',
	`temVinculoFamiliar` int DEFAULT 0,
	`fonteOrigem` varchar(100),
	`idFonteOrigem` varchar(100),
	`dataAtualizacao` timestamp DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	`ativo` int DEFAULT 1,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `contratos_id` PRIMARY KEY(`id`),
	CONSTRAINT `contratos_numeroContrato_unique` UNIQUE(`numeroContrato`)
);
--> statement-breakpoint
CREATE TABLE `emendas` (
	`id` int AUTO_INCREMENT NOT NULL,
	`numeroEmenda` varchar(50) NOT NULL,
	`parlamentarId` int,
	`parlamentarNome` varchar(255),
	`valorEmenda` varchar(30) NOT NULL,
	`valorExecutado` varchar(30) DEFAULT '0',
	`municipio` varchar(100),
	`estado` varchar(2),
	`descricao` text,
	`tipoEmenda` varchar(100),
	`scoreRisco` varchar(10) DEFAULT '0',
	`nivelRisco_emenda` enum('baixo','medio','alto','critico') DEFAULT 'baixo',
	`dataEmenda` timestamp,
	`dataExecucao` timestamp,
	`fonteOrigem` varchar(100),
	`idFonteOrigem` varchar(100),
	`dataAtualizacao` timestamp DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	`ativo` int DEFAULT 1,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `emendas_id` PRIMARY KEY(`id`),
	CONSTRAINT `emendas_numeroEmenda_unique` UNIQUE(`numeroEmenda`)
);
--> statement-breakpoint
CREATE TABLE `parlamentares` (
	`id` int AUTO_INCREMENT NOT NULL,
	`cpf` varchar(14) NOT NULL,
	`nome` varchar(255) NOT NULL,
	`partido` varchar(50) NOT NULL,
	`estado` varchar(2) NOT NULL,
	`cargo` varchar(100) NOT NULL,
	`email` varchar(255),
	`telefone` varchar(20),
	`dataPosse` timestamp,
	`dataFim` timestamp,
	`idTSE` varchar(50),
	`numeroInscricao` varchar(20),
	`scoreRisco` varchar(10) DEFAULT '0',
	`nivelRisco` enum('baixo','medio','alto','critico') DEFAULT 'baixo',
	`totalContratos` int DEFAULT 0,
	`totalEmendas` int DEFAULT 0,
	`totalValorContratos` varchar(30) DEFAULT '0',
	`totalValorEmendas` varchar(30) DEFAULT '0',
	`dataAtualizacao` timestamp DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	`ativo` int DEFAULT 1,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `parlamentares_id` PRIMARY KEY(`id`),
	CONSTRAINT `parlamentares_cpf_unique` UNIQUE(`cpf`),
	CONSTRAINT `parlamentares_idTSE_unique` UNIQUE(`idTSE`)
);
